language: node_js
node_js:
  - lts/*
install:
  - npm ci
script:
  - npm run docs:build
deploy:
  provider: pages
  skip-cleanup: true
  local_dir: docs/.vuepress/dist
  github-token: d1705a6e54376bfcbd82718a04be24e74fcfb06f
  keep-history: true
  on:
    branch: master
