language: node_js
node_js:
  - lts/*
install:
  - npm ci
script:
  - npm run docs:build
deploy:
  provider: pages
  skip-cleanup: true
  local_dir: docs/.vuepress/dist
  github-token: 51e68f68b337ce56646fe828fc6fa01f241ba0f4
  keep-history: true
  on:
    branch: master
